# Generated by Django 4.0.3 on 2022-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='upload/products/')),
            ],
        ),
    ]
